/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { MedicalRecordsService } from './medical-records.service';
export * from './models/medical-record-dto';
export * from './models/save-medical-record-command';
