/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { MedicalRecordDto } from './models/medical-record-dto';
import type { SaveMedicalRecordCommand } from './models/save-medical-record-command';

@Injectable({ providedIn: 'root' })
export class MedicalRecordsService extends ApiClient {
  medicalRecords() {
    return this.http.get<MedicalRecordDto[]>(`${this.base}/api/historias-medicas`);
  }

  medicalRecord(patientId: string) {
    return this.http.get<MedicalRecordDto>(`${this.base}/api/historias-medicas/${patientId}`);
  }

  saveMedicalRecord(patientId: string, body: SaveMedicalRecordCommand) {
    return this.http.put<MedicalRecordDto>(`${this.base}/api/historias-medicas/${patientId}`, body);
  }
}
