/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { TenantRole } from './tenant-role';

export interface CreatedEmployeeDto {
  row: number;
  email: string;
  temporaryPassword: string;
  role: TenantRole;
}
