/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { CreatedEmployeeDto } from './created-employee-dto';
import type { RejectedRowDto } from './rejected-row-dto';

export interface EmployeeImportDto {
  created: CreatedEmployeeDto[];
  rejected: RejectedRowDto[];
}
