/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface ProfessionalDto {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  licenseNumber?: string | null;
  specialtyId?: string | null;
}
