/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { CLINICA_API_URL } from './tokens';

export type TenantType = "Practice" | "Hospital";

export type TenantStatus = "Active" | "Suspended" | "Deactivated";

export type TenantRole = "TenantAdmin" | "Doctor" | "Secretary" | "Patient";

export type AppointmentStatus = "Booked" | "CheckedIn" | "InProgress" | "Completed" | "Cancelled" | "NoShow";

export type WaitlistStatus = "Pending" | "Offered" | "Accepted" | "Cancelled";

export type PaymentMethod = "Cash" | "Transfer" | "Card";

export type InvoiceStatus = "Pending" | "Paid" | "Voided";

export type DayOfWeek = "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";

export interface LoginCommand {
  email: string;
  password: string;
}

export interface TokenDto {
  token: string;
  email: string;
  name: string;
  role: string;
  tenantSlug?: string | null;
  mustChangePassword: boolean;
}

export interface CreateTenantCommand {
  slug: string;
  name: string;
  type: TenantType;
}

export interface ChangeTenantStatusCommand {
  status: TenantStatus;
}

export interface TenantDto {
  id: string;
  slug: string;
  name: string;
  type: TenantType;
  status: TenantStatus;
  createdAt: string;
}

export interface RegisterPatientCommand {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
}

export interface LocationDto {
  id: string;
  name: string;
  address: string;
  isActive: boolean;
}

export interface SaveLocationCommand {
  name: string;
  address: string;
}

export interface MedicalServiceDto {
  id: string;
  locationId: string;
  name: string;
}

export interface SaveMedicalServiceCommand {
  locationId: string;
  name: string;
}

export interface SpecialtyDto {
  id: string;
  name: string;
}

export interface SaveSpecialtyCommand {
  name: string;
}

export interface AppointmentTypeDto {
  id: string;
  name: string;
  durationMinutes: number;
  specialtyId?: string | null;
}

export interface SaveAppointmentTypeCommand {
  name: string;
  durationMinutes: number;
  specialtyId?: string | null;
}

export interface ProfessionalDto {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  licenseNumber?: string | null;
  specialtyId?: string | null;
}

export interface ImportEmployeesCommand {
  csv: string;
}

export interface CreatedEmployeeDto {
  row: number;
  email: string;
  temporaryPassword: string;
  role: TenantRole;
}

export interface RejectedRowDto {
  row: number;
  reason: string;
}

export interface EmployeeImportDto {
  created: CreatedEmployeeDto[];
  rejected: RejectedRowDto[];
}

export interface ScheduleBlockDto {
  id: string;
  day: DayOfWeek;
  startTime: string;
  endTime: string;
  locationId: string;
  appointmentTypeId: string;
}

export interface SaveScheduleCommand {
  professionalId: string;
  blocks: ScheduleBlockDto[];
}

export interface BlockoutDto {
  id: string;
  professionalId: string;
  start: string;
  end: string;
  reason: string;
}

export interface CreateBlockoutCommand {
  professionalId: string;
  start: string;
  end: string;
  reason: string;
}

export interface SlotDto {
  professionalId: string;
  professional: string;
  locationId: string;
  appointmentTypeId: string;
  appointmentType: string;
  start: string;
  end: string;
}

export interface BookAppointmentCommand {
  patientId?: string | null;
  professionalId: string;
  locationId: string;
  appointmentTypeId: string;
  start: string;
  visitReason?: string | null;
}

export interface AppointmentDto {
  id: string;
  patientId: string;
  patient: string;
  professionalId: string;
  professional: string;
  locationId: string;
  location: string;
  appointmentTypeId: string;
  appointmentType: string;
  start: string;
  end: string;
  status: AppointmentStatus;
  visitReason?: string | null;
}

export interface RescheduleAppointmentCommand {
  start: string;
}

export interface WaitlistEntryDto {
  id: string;
  patientId: string;
  patient: string;
  professionalId?: string | null;
  locationId: string;
  specialtyId: string;
  status: WaitlistStatus;
  createdAt: string;
  notes?: string | null;
}

export interface CreateWaitlistEntryCommand {
  patientId?: string | null;
  professionalId?: string | null;
  locationId: string;
  specialtyId: string;
  notes?: string | null;
}

export interface AssignWaitlistEntryCommand {
  start: string;
  appointmentTypeId: string;
}

export interface DiagnosisDto {
  id: string;
  code: string;
  name: string;
}

export interface SaveEncounterCommand {
  appointmentId: string;
  note?: string | null;
  bloodPressure?: string | null;
  heartRate?: number | null;
  temperature?: number | null;
  weightKg?: number | null;
  diagnosisIds: string[];
}

export interface EncounterDto {
  id: string;
  appointmentId: string;
  patientId: string;
  professionalId: string;
  note?: string | null;
  bloodPressure?: string | null;
  heartRate?: number | null;
  temperature?: number | null;
  weightKg?: number | null;
  isClosed: boolean;
  createdAt: string;
  diagnoses: DiagnosisDto[];
}

export interface PrescriptionItemDto {
  medication: string;
  dose: string;
  frequency: string;
  duration: string;
}

export interface CreatePrescriptionCommand {
  encounterId: string;
  instructions?: string | null;
  items: PrescriptionItemDto[];
}

export interface PrescriptionDto {
  id: string;
  encounterId: string;
  patientId: string;
  professionalId: string;
  professional: string;
  instructions?: string | null;
  createdAt: string;
  items: PrescriptionItemDto[];
}

export interface PatientSummaryDto {
  id: string;
  name: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
}

export interface ClinicalHistoryDto {
  patient: PatientSummaryDto;
  encounters: EncounterDto[];
  prescriptions: PrescriptionDto[];
}

export interface MedicalRecordDto {
  patientId: string;
  firstName: string;
  lastName: string;
  email: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
  bloodType?: string | null;
  allergies?: string | null;
  personalHistory?: string | null;
  familyHistory?: string | null;
  currentMedication?: string | null;
  habits?: string | null;
  healthInsurance?: string | null;
  memberNumber?: string | null;
  emergencyContact?: string | null;
  emergencyPhone?: string | null;
  notes?: string | null;
  updatedAt?: string | null;
}

export interface SaveMedicalRecordCommand {
  firstName: string;
  lastName: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
  bloodType?: string | null;
  allergies?: string | null;
  personalHistory?: string | null;
  familyHistory?: string | null;
  currentMedication?: string | null;
  habits?: string | null;
  healthInsurance?: string | null;
  memberNumber?: string | null;
  emergencyContact?: string | null;
  emergencyPhone?: string | null;
  notes?: string | null;
}

export interface FeeDto {
  id: string;
  appointmentTypeId: string;
  appointmentType: string;
  amount: number;
  effectiveFrom: string;
}

export interface CreateFeeCommand {
  appointmentTypeId: string;
  amount: number;
  effectiveFrom: string;
}

export interface InvoiceItemDto {
  description: string;
  amount: number;
}

export interface InvoiceDto {
  id: string;
  appointmentId: string;
  patientId: string;
  patient: string;
  total: number;
  status: InvoiceStatus;
  paymentMethod?: PaymentMethod | null;
  createdAt: string;
  paidAt?: string | null;
  items: InvoiceItemDto[];
}

export interface PayInvoiceCommand {
  method: PaymentMethod;
}

export interface AuditEntryDto {
  id: string;
  userId?: string | null;
  action: string;
  entity: string;
  entityId?: string | null;
  detail?: string | null;
  timestamp: string;
}

@Injectable({ providedIn: 'root' })
export class ClinicaClient {
  private readonly http = inject(HttpClient);
  private readonly base = inject(CLINICA_API_URL);

  private queryString(query?: Record<string, unknown>) {
    if (!query) return '';
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null && value !== '') params.set(key, String(value));
    }
    const text = params.toString();
    return text ? `?${text}` : '';
  }

  platformLogin(body: LoginCommand) {
    return this.http.post<TokenDto>(`${this.base}/api/plataforma/acceso/ingreso`, body);
  }

  listTenants() {
    return this.http.get<TenantDto[]>(`${this.base}/api/plataforma/consultorios`);
  }

  createTenant(body: CreateTenantCommand) {
    return this.http.post<TenantDto>(`${this.base}/api/plataforma/consultorios`, body);
  }

  changeTenantStatus(id: string, body: ChangeTenantStatusCommand) {
    return this.http.patch<TenantDto>(`${this.base}/api/plataforma/consultorios/${id}/estado`, body);
  }

  tenantLogin(body: LoginCommand) {
    return this.http.post<TokenDto>(`${this.base}/api/acceso/ingreso`, body);
  }

  registerPatient(body: RegisterPatientCommand) {
    return this.http.post<TokenDto>(`${this.base}/api/acceso/registro`, body);
  }

  locations() {
    return this.http.get<LocationDto[]>(`${this.base}/api/sedes`);
  }

  createLocation(body: SaveLocationCommand) {
    return this.http.post<LocationDto>(`${this.base}/api/sedes`, body);
  }

  updateLocation(id: string, body: SaveLocationCommand) {
    return this.http.put<LocationDto>(`${this.base}/api/sedes/${id}`, body);
  }

  medicalServices() {
    return this.http.get<MedicalServiceDto[]>(`${this.base}/api/servicios`);
  }

  createMedicalService(body: SaveMedicalServiceCommand) {
    return this.http.post<MedicalServiceDto>(`${this.base}/api/servicios`, body);
  }

  specialties() {
    return this.http.get<SpecialtyDto[]>(`${this.base}/api/especialidades`);
  }

  createSpecialty(body: SaveSpecialtyCommand) {
    return this.http.post<SpecialtyDto>(`${this.base}/api/especialidades`, body);
  }

  appointmentTypes() {
    return this.http.get<AppointmentTypeDto[]>(`${this.base}/api/tipos-turno`);
  }

  createAppointmentType(body: SaveAppointmentTypeCommand) {
    return this.http.post<AppointmentTypeDto>(`${this.base}/api/tipos-turno`, body);
  }

  professionals(query?: { specialtyId?: string }) {
    return this.http.get<ProfessionalDto[]>(`${this.base}/api/profesionales` + this.queryString(query));
  }

  importEmployees(body: ImportEmployeesCommand) {
    return this.http.post<EmployeeImportDto>(`${this.base}/api/empleados/importar`, body);
  }

  getSchedule(query: { professionalId: string }) {
    return this.http.get<ScheduleBlockDto[]>(`${this.base}/api/agendas` + this.queryString(query));
  }

  saveSchedule(body: SaveScheduleCommand) {
    return this.http.put<ScheduleBlockDto[]>(`${this.base}/api/agendas`, body);
  }

  blockouts(query: { professionalId: string }) {
    return this.http.get<BlockoutDto[]>(`${this.base}/api/bloqueos` + this.queryString(query));
  }

  createBlockout(body: CreateBlockoutCommand) {
    return this.http.post<BlockoutDto>(`${this.base}/api/bloqueos`, body);
  }

  deleteBlockout(id: string) {
    return this.http.delete<void>(`${this.base}/api/bloqueos/${id}`);
  }

  availability(query: { locationId: string; specialtyId: string; professionalId?: string; date: string }) {
    return this.http.get<SlotDto[]>(`${this.base}/api/disponibilidad` + this.queryString(query));
  }

  appointmentsForDay(query: { date: string; professionalId?: string }) {
    return this.http.get<AppointmentDto[]>(`${this.base}/api/turnos` + this.queryString(query));
  }

  bookAppointment(body: BookAppointmentCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos`, body);
  }

  myAppointments() {
    return this.http.get<AppointmentDto[]>(`${this.base}/api/turnos/mios`);
  }

  cancelAppointment(id: string) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/cancelar`, {});
  }

  checkInAppointment(id: string) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/admitir`, {});
  }

  rescheduleAppointment(id: string, body: RescheduleAppointmentCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/reprogramar`, body);
  }

  waitlist() {
    return this.http.get<WaitlistEntryDto[]>(`${this.base}/api/lista-espera`);
  }

  joinWaitlist(body: CreateWaitlistEntryCommand) {
    return this.http.post<WaitlistEntryDto>(`${this.base}/api/lista-espera`, body);
  }

  assignWaitlistEntry(id: string, body: AssignWaitlistEntryCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/lista-espera/${id}/asignar`, body);
  }

  diagnoses() {
    return this.http.get<DiagnosisDto[]>(`${this.base}/api/diagnosticos`);
  }

  saveEncounter(body: SaveEncounterCommand) {
    return this.http.post<EncounterDto>(`${this.base}/api/encuentros`, body);
  }

  closeEncounter(id: string) {
    return this.http.post<EncounterDto>(`${this.base}/api/encuentros/${id}/cerrar`, {});
  }

  createPrescription(body: CreatePrescriptionCommand) {
    return this.http.post<PrescriptionDto>(`${this.base}/api/recetas`, body);
  }

  myPrescriptions() {
    return this.http.get<PrescriptionDto[]>(`${this.base}/api/recetas/mias`);
  }

  getPrescription(id: string) {
    return this.http.get<PrescriptionDto>(`${this.base}/api/recetas/${id}`);
  }

  clinicalHistory(query?: { patientId?: string }) {
    return this.http.get<ClinicalHistoryDto>(`${this.base}/api/historia` + this.queryString(query));
  }

  medicalRecords() {
    return this.http.get<MedicalRecordDto[]>(`${this.base}/api/historias-medicas`);
  }

  medicalRecord(patientId: string) {
    return this.http.get<MedicalRecordDto>(`${this.base}/api/historias-medicas/${patientId}`);
  }

  saveMedicalRecord(patientId: string, body: SaveMedicalRecordCommand) {
    return this.http.put<MedicalRecordDto>(`${this.base}/api/historias-medicas/${patientId}`, body);
  }

  fees() {
    return this.http.get<FeeDto[]>(`${this.base}/api/aranceles`);
  }

  createFee(body: CreateFeeCommand) {
    return this.http.post<FeeDto>(`${this.base}/api/aranceles`, body);
  }

  invoices() {
    return this.http.get<InvoiceDto[]>(`${this.base}/api/comprobantes`);
  }

  payInvoice(id: string, body: PayInvoiceCommand) {
    return this.http.post<InvoiceDto>(`${this.base}/api/comprobantes/${id}/pagar`, body);
  }

  auditLog() {
    return this.http.get<AuditEntryDto[]>(`${this.base}/api/auditoria`);
  }
}
