/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { CreateFeeCommand } from './models/create-fee-command';
import type { FeeDto } from './models/fee-dto';
import type { InvoiceDto } from './models/invoice-dto';
import type { PayInvoiceCommand } from './models/pay-invoice-command';

@Injectable({ providedIn: 'root' })
export class BillingService extends ApiClient {
  fees() {
    return this.http.get<FeeDto[]>(`${this.base}/api/aranceles`);
  }

  createFee(body: CreateFeeCommand) {
    return this.http.post<FeeDto>(`${this.base}/api/aranceles`, body);
  }

  invoices() {
    return this.http.get<InvoiceDto[]>(`${this.base}/api/comprobantes`);
  }

  payInvoice(id: string, body: PayInvoiceCommand) {
    return this.http.post<InvoiceDto>(`${this.base}/api/comprobantes/${id}/pagar`, body);
  }
}
