/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { BillingService } from './billing.service';
export * from './models/payment-method';
export * from './models/invoice-status';
export * from './models/fee-dto';
export * from './models/create-fee-command';
export * from './models/invoice-item-dto';
export * from './models/invoice-dto';
export * from './models/pay-invoice-command';
