/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface MedicalRecordDto {
  patientId: string;
  firstName: string;
  lastName: string;
  email: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
  bloodType?: string | null;
  allergies?: string | null;
  personalHistory?: string | null;
  familyHistory?: string | null;
  currentMedication?: string | null;
  habits?: string | null;
  healthInsurance?: string | null;
  memberNumber?: string | null;
  emergencyContact?: string | null;
  emergencyPhone?: string | null;
  notes?: string | null;
  updatedAt?: string | null;
}
