services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinica
      POSTGRES_DB: clinica_catalog
    ports:
      - "5432:5432"
    volumes:
      - clinica_pg:/var/lib/postgresql

volumes:
  clinica_pg:
