/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { EncounterDto } from './encounter-dto';
import type { PatientSummaryDto } from './patient-summary-dto';
import type { PrescriptionDto } from './prescription-dto';

export interface ClinicalHistoryDto {
  patient: PatientSummaryDto;
  encounters: EncounterDto[];
  prescriptions: PrescriptionDto[];
}
