/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { PrescriptionItemDto } from './prescription-item-dto';

export interface CreatePrescriptionCommand {
  encounterId: string;
  instructions?: string | null;
  items: PrescriptionItemDto[];
}
