/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { DiagnosisDto } from './diagnosis-dto';

export interface EncounterDto {
  id: string;
  appointmentId: string;
  patientId: string;
  professionalId: string;
  note?: string | null;
  bloodPressure?: string | null;
  heartRate?: number | null;
  temperature?: number | null;
  weightKg?: number | null;
  isClosed: boolean;
  createdAt: string;
  diagnoses: DiagnosisDto[];
}
