/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface PatientSummaryDto {
  id: string;
  name: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
}
