/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { PrescriptionItemDto } from './prescription-item-dto';

export interface PrescriptionDto {
  id: string;
  encounterId: string;
  patientId: string;
  professionalId: string;
  professional: string;
  instructions?: string | null;
  createdAt: string;
  items: PrescriptionItemDto[];
}
