/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface PrescriptionItemDto {
  medication: string;
  dose: string;
  frequency: string;
  duration: string;
}
