/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { LoginCommand } from './models/login-command';
import type { RegisterPatientCommand } from './models/register-patient-command';
import type { TokenDto } from './models/token-dto';

@Injectable({ providedIn: 'root' })
export class AuthService extends ApiClient {
  login(body: LoginCommand) {
    return this.http.post<TokenDto>(`${this.base}/api/acceso/ingreso`, body);
  }

  registerPatient(body: RegisterPatientCommand) {
    return this.http.post<TokenDto>(`${this.base}/api/acceso/registro`, body);
  }
}
