/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { AuthService } from './auth.service';
export * from './models/login-command';
export * from './models/token-dto';
export * from './models/register-patient-command';
