/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { MedicalRecordDto } from '../../medical-records/models/medical-record-dto';

export interface CreatedPatientDto {
  patient: MedicalRecordDto;
  temporaryPassword: string;
}
