/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface PatientLookupDto {
  patientId: string;
  firstName: string;
  lastName: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
  healthInsurance?: string | null;
  memberNumber?: string | null;
  emergencyContact?: string | null;
  emergencyPhone?: string | null;
}
