/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface CreateBlockoutCommand {
  professionalId: string;
  start: string;
  end: string;
  reason: string;
}
