/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export type DayOfWeek = "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";
