/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { ScheduleBlockDto } from './schedule-block-dto';

export interface SaveScheduleCommand {
  professionalId: string;
  blocks: ScheduleBlockDto[];
}
