/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { DayOfWeek } from './day-of-week';

export interface ScheduleBlockDto {
  id: string;
  day: DayOfWeek;
  startTime: string;
  endTime: string;
  locationId: string;
  appointmentTypeId: string;
}
