/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface SlotDto {
  professionalId: string;
  professional: string;
  locationId: string;
  appointmentTypeId: string;
  appointmentType: string;
  start: string;
  end: string;
}
