/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import { queryString } from '../../core/query-string';
import type { ClinicalHistoryDto } from './models/clinical-history-dto';
import type { CreatePrescriptionCommand } from './models/create-prescription-command';
import type { DiagnosisDto } from './models/diagnosis-dto';
import type { EncounterDto } from './models/encounter-dto';
import type { PrescriptionDto } from './models/prescription-dto';
import type { SaveEncounterCommand } from './models/save-encounter-command';

@Injectable({ providedIn: 'root' })
export class ClinicalService extends ApiClient {
  diagnoses() {
    return this.http.get<DiagnosisDto[]>(`${this.base}/api/diagnosticos`);
  }

  saveEncounter(body: SaveEncounterCommand) {
    return this.http.post<EncounterDto>(`${this.base}/api/encuentros`, body);
  }

  closeEncounter(id: string) {
    return this.http.post<EncounterDto>(`${this.base}/api/encuentros/${id}/cerrar`, {});
  }

  createPrescription(body: CreatePrescriptionCommand) {
    return this.http.post<PrescriptionDto>(`${this.base}/api/recetas`, body);
  }

  myPrescriptions() {
    return this.http.get<PrescriptionDto[]>(`${this.base}/api/recetas/mias`);
  }

  getPrescription(id: string) {
    return this.http.get<PrescriptionDto>(`${this.base}/api/recetas/${id}`);
  }

  clinicalHistory(query?: { patientId?: string }) {
    return this.http.get<ClinicalHistoryDto>(`${this.base}/api/historia${queryString(query)}`);
  }
}
