/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { ClinicalService } from './clinical.service';
export * from './models/diagnosis-dto';
export * from './models/save-encounter-command';
export * from './models/encounter-dto';
export * from './models/prescription-item-dto';
export * from './models/create-prescription-command';
export * from './models/prescription-dto';
export * from './models/patient-summary-dto';
export * from './models/clinical-history-dto';
