/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { OrganizationService } from './organization.service';
export * from './models/location-dto';
export * from './models/save-location-command';
export * from './models/medical-service-dto';
export * from './models/save-medical-service-command';
export * from './models/specialty-dto';
export * from './models/save-specialty-command';
export * from './models/appointment-type-dto';
export * from './models/save-appointment-type-command';
