/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { AppointmentTypeDto } from './models/appointment-type-dto';
import type { LocationDto } from './models/location-dto';
import type { MedicalServiceDto } from './models/medical-service-dto';
import type { SaveAppointmentTypeCommand } from './models/save-appointment-type-command';
import type { SaveLocationCommand } from './models/save-location-command';
import type { SaveMedicalServiceCommand } from './models/save-medical-service-command';
import type { SaveSpecialtyCommand } from './models/save-specialty-command';
import type { SpecialtyDto } from './models/specialty-dto';

@Injectable({ providedIn: 'root' })
export class OrganizationService extends ApiClient {
  locations() {
    return this.http.get<LocationDto[]>(`${this.base}/api/sedes`);
  }

  createLocation(body: SaveLocationCommand) {
    return this.http.post<LocationDto>(`${this.base}/api/sedes`, body);
  }

  updateLocation(id: string, body: SaveLocationCommand) {
    return this.http.put<LocationDto>(`${this.base}/api/sedes/${id}`, body);
  }

  medicalServices() {
    return this.http.get<MedicalServiceDto[]>(`${this.base}/api/servicios`);
  }

  createMedicalService(body: SaveMedicalServiceCommand) {
    return this.http.post<MedicalServiceDto>(`${this.base}/api/servicios`, body);
  }

  specialties() {
    return this.http.get<SpecialtyDto[]>(`${this.base}/api/especialidades`);
  }

  createSpecialty(body: SaveSpecialtyCommand) {
    return this.http.post<SpecialtyDto>(`${this.base}/api/especialidades`, body);
  }

  appointmentTypes() {
    return this.http.get<AppointmentTypeDto[]>(`${this.base}/api/tipos-turno`);
  }

  createAppointmentType(body: SaveAppointmentTypeCommand) {
    return this.http.post<AppointmentTypeDto>(`${this.base}/api/tipos-turno`, body);
  }

  updateAppointmentType(id: string, body: SaveAppointmentTypeCommand) {
    return this.http.put<AppointmentTypeDto>(`${this.base}/api/tipos-turno/${id}`, body);
  }
}
