import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const spec = JSON.parse(readFileSync(join(root, '../openapi/clinica.json'), 'utf8'));
const modulesDir = join(root, '../projects/sdk/src/lib/modules');
const header = '/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */\n';

const modules = [
  {
    id: 'auth',
    service: 'AuthService',
    match: (path) => path.startsWith('/api/plataforma/acceso') || path.startsWith('/api/acceso'),
  },
  {
    id: 'tenants',
    service: 'TenantsService',
    match: (path) => path.startsWith('/api/plataforma/consultorios'),
  },
  {
    id: 'organization',
    service: 'OrganizationService',
    match: (path) => ['/api/sedes', '/api/servicios', '/api/especialidades', '/api/tipos-turno'].some((prefix) => path === prefix || path.startsWith(`${prefix}/`)),
  },
  {
    id: 'employees',
    service: 'EmployeesService',
    match: (path) => path.startsWith('/api/profesionales') || path.startsWith('/api/empleados'),
  },
  {
    id: 'schedule',
    service: 'ScheduleService',
    match: (path) => path.startsWith('/api/agendas') || path.startsWith('/api/bloqueos') || path.startsWith('/api/disponibilidad'),
  },
  {
    id: 'appointments',
    service: 'AppointmentsService',
    match: (path) => path.startsWith('/api/turnos') || path.startsWith('/api/lista-espera'),
  },
  {
    id: 'clinical',
    service: 'ClinicalService',
    match: (path) =>
      path.startsWith('/api/diagnosticos') ||
      path.startsWith('/api/encuentros') ||
      path.startsWith('/api/recetas') ||
      path === '/api/historia' ||
      path.startsWith('/api/historia/'),
  },
  {
    id: 'patients',
    service: 'PatientsService',
    match: (path) => path.startsWith('/api/pacientes'),
  },
  {
    id: 'medical-records',
    service: 'MedicalRecordsService',
    match: (path) => path.startsWith('/api/historias-medicas'),
  },
  {
    id: 'billing',
    service: 'BillingService',
    match: (path) => path.startsWith('/api/aranceles') || path.startsWith('/api/comprobantes'),
  },
  {
    id: 'audit',
    service: 'AuditService',
    match: (path) => path.startsWith('/api/auditoria'),
  },
];

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function refName(schema) {
  return schema?.$ref?.split('/').pop() ?? null;
}

function walkRefs(schema, acc) {
  if (!schema || typeof schema !== 'object') return;
  const name = refName(schema);
  if (name) acc.add(name);
  for (const key of ['allOf', 'oneOf', 'anyOf']) {
    for (const item of schema[key] ?? []) walkRefs(item, acc);
  }
  if (schema.items) walkRefs(schema.items, acc);
  if (schema.properties) {
    for (const prop of Object.values(schema.properties)) walkRefs(prop, acc);
  }
}

function tsType(schema) {
  if (!schema) return 'void';
  if (schema.$ref) return refName(schema);
  if (schema.allOf) return tsType(schema.allOf[0]);
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
  if (schema.type === 'array') return `${tsType(schema.items)}[]`;
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'string') return 'string';
  return 'unknown';
}

function collectRefs(schema) {
  const acc = new Set();
  walkRefs(schema, acc);
  return acc;
}

function modelImport(moduleId, typeName) {
  const target = owner.get(typeName);
  const file = kebab(typeName);
  return target === moduleId ? `./${file}` : `../../${target}/models/${file}`;
}

function emitModel(moduleId, name, schema) {
  if (schema.enum) {
    return `${header}export type ${name} = ${schema.enum.map((value) => JSON.stringify(value)).join(' | ')};\n`;
  }
  const required = new Set(schema.required ?? []);
  const refs = [...collectRefs(schema)].filter((ref) => ref !== name);
  const imports = refs
    .sort()
    .map((ref) => `import type { ${ref} } from '${modelImport(moduleId, ref)}';`)
    .join('\n');
  const fields = Object.entries(schema.properties ?? {}).map(([prop, def]) => {
    const optional = required.has(prop) ? '' : '?';
    const nullable = def.nullable ? ' | null' : '';
    return `  ${prop}${optional}: ${tsType(def)}${nullable};`;
  });
  const body = `export interface ${name} {\n${fields.join('\n')}\n}\n`;
  return `${header}${imports ? `${imports}\n\n` : ''}${body}`;
}

function moduleOf(path) {
  return modules.find((module) => module.match(path));
}

const operations = [];
for (const [path, verbs] of Object.entries(spec.paths)) {
  const module = moduleOf(path);
  if (!module) throw new Error(`Ruta sin módulo: ${path}`);
  for (const [verb, op] of Object.entries(verbs)) operations.push({ path, verb, op, module });
}

const owner = new Map();
const queue = [];
for (const { op, module } of operations) {
  const refs = new Set();
  walkRefs(op.requestBody?.content?.['application/json']?.schema, refs);
  for (const response of Object.values(op.responses ?? {})) walkRefs(response.content?.['application/json']?.schema, refs);
  for (const name of refs) {
    if (owner.has(name)) continue;
    owner.set(name, module.id);
    queue.push(name);
  }
}
while (queue.length) {
  const name = queue.shift();
  const moduleId = owner.get(name);
  const refs = new Set();
  walkRefs(spec.components.schemas[name], refs);
  for (const ref of refs) {
    if (owner.has(ref)) continue;
    owner.set(ref, moduleId);
    queue.push(ref);
  }
}
for (const name of Object.keys(spec.components.schemas)) {
  if (!owner.has(name)) throw new Error(`Schema sin módulo: ${name}`);
}

function emitMethod(item) {
  const { path, verb, op } = item;
  const params = (op.parameters ?? []).filter((parameter) => parameter.in === 'path');
  const query = (op.parameters ?? []).filter((parameter) => parameter.in === 'query');
  const body = op.requestBody?.content?.['application/json']?.schema;
  const response =
    op.responses?.['200']?.content?.['application/json']?.schema ?? op.responses?.['201']?.content?.['application/json']?.schema;
  const args = params.map((parameter) => `${parameter.name}: ${tsType(parameter.schema)}`);
  if (body) args.push(`body: ${tsType(body)}`);
  if (query.length) {
    const fields = query.map((parameter) => `${parameter.name}${parameter.required ? '' : '?'}: ${tsType(parameter.schema)}`).join('; ');
    const optional = query.some((parameter) => parameter.required) ? '' : '?';
    args.push(`query${optional}: { ${fields} }`);
  }
  const responseType = response ? tsType(response) : 'void';
  const pathExpr = path.replaceAll(/\{([^}]+)\}/g, '${$1}');
  const queryExpr = query.length ? '${queryString(query)}' : '';
  const url = `\`\${this.base}${pathExpr}${queryExpr}\``;
  const call =
    verb === 'get' || verb === 'delete'
      ? `this.http.${verb}<${responseType}>(${url})`
      : `this.http.${verb}<${responseType}>(${url}, ${body ? 'body' : '{}'})`;
  const used = new Set();
  walkRefs(body, used);
  walkRefs(response, used);
  return { source: `  ${op.operationId}(${args.join(', ')}) {\n    return ${call};\n  }`, used, hasQuery: query.length > 0 };
}

rmSync(modulesDir, { recursive: true, force: true });

const publicExports = ["export * from './lib/core/api-client';", "export * from './lib/core/session';"];

for (const module of modules) {
  const dir = join(modulesDir, module.id);
  const modelsDir = join(dir, 'models');
  mkdirSync(modelsDir, { recursive: true });
  const schemas = Object.keys(spec.components.schemas).filter((name) => owner.get(name) === module.id);
  const modelExports = [];
  for (const name of schemas) {
    const file = `${kebab(name)}.ts`;
    writeFileSync(join(modelsDir, file), emitModel(module.id, name, spec.components.schemas[name]));
    modelExports.push(`export * from './models/${kebab(name)}';`);
  }

  const methods = operations.filter((item) => item.module.id === module.id).map(emitMethod);
  const used = new Set(methods.flatMap((method) => [...method.used]));
  const imports = [
    "import { Injectable } from '@angular/core';",
    "import { ApiClient } from '../../core/api-client';",
    methods.some((method) => method.hasQuery) ? "import { queryString } from '../../core/query-string';" : '',
    ...[...used].sort().map((name) => {
      const target = owner.get(name);
      const file = kebab(name);
      const from = target === module.id ? `./models/${file}` : `../${target}/models/${file}`;
      return `import type { ${name} } from '${from}';`;
    }),
  ].filter(Boolean);
  const service = `${header}${imports.join('\n')}\n\n@Injectable({ providedIn: 'root' })\nexport class ${module.service} extends ApiClient {\n${methods.map((method) => method.source).join('\n\n')}\n}\n`;
  writeFileSync(join(dir, `${module.id}.service.ts`), service);
  writeFileSync(join(dir, 'index.ts'), `${header}export { ${module.service} } from './${module.id}.service';\n${modelExports.join('\n')}\n`);
  publicExports.push(`export * from './lib/modules/${module.id}';`);
}

writeFileSync(join(root, '../projects/sdk/src/public-api.ts'), `${header}${publicExports.join('\n')}\n`);
for (const file of ['clinica-client.ts', 'labels.ts', 'sdk.ts', 'tokens.ts', 'session.ts']) {
  rmSync(join(root, '../projects/sdk/src/lib', file), { force: true });
}
console.log('SDK generated');
