/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export type AppointmentStatus = "Booked" | "CheckedIn" | "InProgress" | "Completed" | "Cancelled" | "NoShow";
