/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { AppointmentStatus } from './appointment-status';

export interface AppointmentDto {
  id: string;
  patientId: string;
  patient: string;
  professionalId: string;
  professional: string;
  locationId: string;
  location: string;
  appointmentTypeId: string;
  appointmentType: string;
  start: string;
  end: string;
  status: AppointmentStatus;
  visitReason?: string | null;
}
