/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface BookAppointmentCommand {
  patientId?: string | null;
  professionalId: string;
  locationId: string;
  appointmentTypeId: string;
  start: string;
  visitReason?: string | null;
}
