/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface CreateWaitlistEntryCommand {
  patientId?: string | null;
  professionalId?: string | null;
  locationId: string;
  specialtyId: string;
  notes?: string | null;
}
