/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { WaitlistStatus } from './waitlist-status';

export interface WaitlistEntryDto {
  id: string;
  patientId: string;
  patient: string;
  professionalId?: string | null;
  locationId: string;
  specialtyId: string;
  status: WaitlistStatus;
  createdAt: string;
  notes?: string | null;
}
