/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface RegisterPatientCommand {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  documentNumber: string;
  birthDate: string;
  phone: string;
}
