/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface TokenDto {
  token: string;
  email: string;
  name: string;
  role: string;
  tenantSlug?: string | null;
  mustChangePassword: boolean;
}
