/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { TenantsService } from './tenants.service';
export * from './models/tenant-type';
export * from './models/tenant-status';
export * from './models/create-tenant-command';
export * from './models/change-tenant-status-command';
export * from './models/tenant-dto';
