/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { ChangeTenantStatusCommand } from './models/change-tenant-status-command';
import type { CreateTenantCommand } from './models/create-tenant-command';
import type { TenantDto } from './models/tenant-dto';

@Injectable({ providedIn: 'root' })
export class TenantsService extends ApiClient {
  listTenants() {
    return this.http.get<TenantDto[]>(`${this.base}/api/plataforma/consultorios`);
  }

  createTenant(body: CreateTenantCommand) {
    return this.http.post<TenantDto>(`${this.base}/api/plataforma/consultorios`, body);
  }

  changeTenantStatus(id: string, body: ChangeTenantStatusCommand) {
    return this.http.patch<TenantDto>(`${this.base}/api/plataforma/consultorios/${id}/estado`, body);
  }
}
