/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { ScheduleService } from './schedule.service';
export * from './models/day-of-week';
export * from './models/schedule-block-dto';
export * from './models/save-schedule-command';
export * from './models/blockout-dto';
export * from './models/create-blockout-command';
export * from './models/slot-dto';
