/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import { queryString } from '../../core/query-string';
import type { BlockoutDto } from './models/blockout-dto';
import type { CreateBlockoutCommand } from './models/create-blockout-command';
import type { SaveScheduleCommand } from './models/save-schedule-command';
import type { ScheduleBlockDto } from './models/schedule-block-dto';
import type { SlotDto } from './models/slot-dto';

@Injectable({ providedIn: 'root' })
export class ScheduleService extends ApiClient {
  getSchedule(query: { professionalId: string }) {
    return this.http.get<ScheduleBlockDto[]>(`${this.base}/api/agendas${queryString(query)}`);
  }

  saveSchedule(body: SaveScheduleCommand) {
    return this.http.put<ScheduleBlockDto[]>(`${this.base}/api/agendas`, body);
  }

  blockouts(query: { professionalId: string }) {
    return this.http.get<BlockoutDto[]>(`${this.base}/api/bloqueos${queryString(query)}`);
  }

  createBlockout(body: CreateBlockoutCommand) {
    return this.http.post<BlockoutDto>(`${this.base}/api/bloqueos`, body);
  }

  deleteBlockout(id: string) {
    return this.http.delete<void>(`${this.base}/api/bloqueos/${id}`);
  }

  availability(query: { locationId: string; specialtyId: string; professionalId?: string; date: string }) {
    return this.http.get<SlotDto[]>(`${this.base}/api/disponibilidad${queryString(query)}`);
  }
}
