/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { ClinicDto } from './models/clinic-dto';

@Injectable({ providedIn: 'root' })
export class ClinicService extends ApiClient {
  clinicProfile() {
    return this.http.get<ClinicDto>(`${this.base}/api/clinica`);
  }
}
