/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface AppointmentTypeDto {
  id: string;
  name: string;
  durationMinutes: number;
  specialtyId?: string | null;
}
