/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface SaveAppointmentTypeCommand {
  name: string;
  durationMinutes: number;
  specialtyId?: string | null;
}
