/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { PatientsService } from './patients.service';
export * from './models/create-patient-command';
export * from './models/created-patient-dto';
export * from './models/patient-lookup-dto';
