/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import { queryString } from '../../core/query-string';
import type { CreatePatientCommand } from './models/create-patient-command';
import type { CreatedPatientDto } from './models/created-patient-dto';
import type { PatientLookupDto } from './models/patient-lookup-dto';

@Injectable({ providedIn: 'root' })
export class PatientsService extends ApiClient {
  searchPatients(query: { q: string }) {
    return this.http.get<PatientLookupDto[]>(`${this.base}/api/pacientes${queryString(query)}`);
  }

  createPatient(body: CreatePatientCommand) {
    return this.http.post<CreatedPatientDto>(`${this.base}/api/pacientes`, body);
  }
}
