/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import type { AuditEntryDto } from './models/audit-entry-dto';

@Injectable({ providedIn: 'root' })
export class AuditService extends ApiClient {
  auditLog() {
    return this.http.get<AuditEntryDto[]>(`${this.base}/api/auditoria`);
  }
}
