/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import { Injectable } from '@angular/core';
import { ApiClient } from '../../core/api-client';
import { queryString } from '../../core/query-string';
import type { AppointmentDto } from './models/appointment-dto';
import type { AssignWaitlistEntryCommand } from './models/assign-waitlist-entry-command';
import type { BookAppointmentCommand } from './models/book-appointment-command';
import type { CreateWaitlistEntryCommand } from './models/create-waitlist-entry-command';
import type { RescheduleAppointmentCommand } from './models/reschedule-appointment-command';
import type { WaitlistEntryDto } from './models/waitlist-entry-dto';

@Injectable({ providedIn: 'root' })
export class AppointmentsService extends ApiClient {
  appointmentsForDay(query: { date: string; professionalId?: string }) {
    return this.http.get<AppointmentDto[]>(`${this.base}/api/turnos${queryString(query)}`);
  }

  bookAppointment(body: BookAppointmentCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos`, body);
  }

  myAppointments() {
    return this.http.get<AppointmentDto[]>(`${this.base}/api/turnos/mios`);
  }

  cancelAppointment(id: string) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/cancelar`, {});
  }

  checkInAppointment(id: string) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/admitir`, {});
  }

  rescheduleAppointment(id: string, body: RescheduleAppointmentCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/turnos/${id}/reprogramar`, body);
  }

  waitlist() {
    return this.http.get<WaitlistEntryDto[]>(`${this.base}/api/lista-espera`);
  }

  joinWaitlist(body: CreateWaitlistEntryCommand) {
    return this.http.post<WaitlistEntryDto>(`${this.base}/api/lista-espera`, body);
  }

  assignWaitlistEntry(id: string, body: AssignWaitlistEntryCommand) {
    return this.http.post<AppointmentDto>(`${this.base}/api/lista-espera/${id}/asignar`, body);
  }
}
