/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export { AppointmentsService } from './appointments.service';
export * from './models/appointment-status';
export * from './models/waitlist-status';
export * from './models/book-appointment-command';
export * from './models/appointment-dto';
export * from './models/reschedule-appointment-command';
export * from './models/waitlist-entry-dto';
export * from './models/create-waitlist-entry-command';
export * from './models/assign-waitlist-entry-command';
