/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface CreateFeeCommand {
  appointmentTypeId: string;
  amount: number;
  effectiveFrom: string;
}
