/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
export interface FeeDto {
  id: string;
  appointmentTypeId: string;
  appointmentType: string;
  amount: number;
  effectiveFrom: string;
}
