/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { InvoiceItemDto } from './invoice-item-dto';
import type { InvoiceStatus } from './invoice-status';
import type { PaymentMethod } from './payment-method';

export interface InvoiceDto {
  id: string;
  appointmentId: string;
  patientId: string;
  patient: string;
  total: number;
  status: InvoiceStatus;
  paymentMethod?: PaymentMethod | null;
  createdAt: string;
  paidAt?: string | null;
  items: InvoiceItemDto[];
}
