/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { PaymentMethod } from './payment-method';

export interface PayInvoiceCommand {
  method: PaymentMethod;
}
