/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { TenantStatus } from './tenant-status';

export interface ChangeTenantStatusCommand {
  status: TenantStatus;
}
