/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { TenantType } from './tenant-type';

export interface CreateTenantCommand {
  slug: string;
  name: string;
  type: TenantType;
}
