/* Generated by scripts/generate-sdk.mjs from openapi/clinica.json. Do not edit by hand. */
import type { TenantStatus } from './tenant-status';
import type { TenantType } from './tenant-type';

export interface TenantDto {
  id: string;
  slug: string;
  name: string;
  type: TenantType;
  status: TenantStatus;
  createdAt: string;
}
